const EMBLEM_POSTS = [
  {
    slug: "landing-the-top-job-nonprofit-executive-search",
    title: "What It Takes to Land the Top Job: Coaching and Connecting for Leaders on the Move",
    date: "2026-04-18",
    dateDisplay: "April 18, 2026",
    readTime: "4 min read",
    tags: ["Executive Search", "Nonprofit Leadership", "Coaching", "Career Transition"],
    excerpt: "The market for nonprofit executive leadership has never been more active or more complicated. CEO searches that used to take three months now take six. Candidates who look strong on paper are losing to candidates who are better prepared and know how to compete.",
    body: `<p>The market for nonprofit executive leadership has never been more active or more complicated. Organizations are navigating federal funding uncertainty, board transitions, and a talent pool more eclectic than ever. CEO searches that used to take three months now take six. Candidates who look strong on paper are losing to candidates who are better prepared and know how to compete. Here&#8217;s what I do with clients at each stage.</p>
<h3>Finding Your Focus</h3>
<p>Most senior leaders know when they want to move up, and some are in the market because they are moving on. Lots of them have done the hard work of identifying where they fit and what they are genuinely competitive for, especially if they are making a pivot. I work with clients to build on what they are already doing, creating an informed and realistic picture of the landscape. We define the right targets, and develop a custom search strategy that has a good chance of working.</p>
<h3>Understanding the Market and Where You Stand</h3>
<p>Candor is rare in this process. Some colleagues, mentors, and well-meaning supporters will be amazing and others may tell you what you want to hear. I will tell you how you are likely to stack up in a competitive field, where your experience is an asset and where it raises questions you&#8217;ll need answers for. We will work on what you need to address before you&#8217;re in a room being evaluated. There are tools you need to be using for this phase and I will introduce you to some while you&#8217;ll of course have already found plenty of others on your own.</p>
<h3>Getting In the Room</h3>
<p>Once you have that focus and the outreach is underway, you need to be sure you are putting your resum&#233; together right &#8211; and doing it custom for any job you really want to get. The only job of the resum&#233; (and cover letter) is to get you a closer look &#8211; to get your chance to tell your story in greater detail. Getting your package pulled out of the pile is half the battle these days.</p>
<h3>Winning the Role</h3>
<p>The core competencies in a job description are the right focal point for any candidate and can be hard to find in the pages of word salad some position profiles include. Still, the relational dimension of executive roles is routinely underweighted by candidates. Boards begin building trust with you in a search process based on how you interact, and the way you address their questions. It&#8217;s not just about the content. And people underestimate that aspect of interviewing every day.</p>
<h3>Coaching and Connecting</h3>
<p>Another thing I do that most coaches won&#8217;t is what I simply call connecting. I go to bat for clients by thinking with them about who in my network they should meet &#8211; for informational conversations or for building their way closer to organizations and fields where they want to find an opportunity. For some clients, this is the most valuable reason to have the right kind of coach.</p>
<p>I&#8217;ve led searches. I&#8217;ve run organizations. I&#8217;ve coached leaders through transitions and maybe most important is that I have been a leader in transition several times. I have made logical progressions and huge pivots. I have had successes and well &#8211; things I would think about doing differently. And my personal experience becomes part of my coaching. My clients get the job done. And they become stronger in ways that go far beyond their first day in the new role.</p>
<p>Know someone who would benefit from this kind of support? Reach me at <a href="mailto:andy@emblemstrategic.com">andy@emblemstrategic.com</a> or through the <a href="https://emblemstrategic.com/#contact">contact page</a> at emblemstrategic.com.</p>`,
  },
  {
    slug: "corporate-citizenship-still-counts",
    title: "Corporate Citizenship Still Counts. New Data Says All Parties Working Together Can Increase Impact.",
    date: "2026-04-07",
    dateDisplay: "April 7, 2026",
    readTime: "4 min read",
    tags: ["Corporate Citizenship", "DEI", "Employee Volunteering", "Nonprofit"],
    excerpt: "The headlines say corporate America is retreating from its commitments. The picture emerging from this spring’s corporate citizenship reporting season is much more complicated than that.",
    body: `<p>The headlines say corporate America is retreating from its commitments. The picture emerging from this spring&#8217;s corporate citizenship reporting season is much more complicated than that. The best place to start is new data.</p>
<p>The Conference Board surveyed corporate citizenship leaders in January, and a summary of its findings is available through the Harvard Law Corporate Governance Forum. Budgets are holding. More than half of respondents expect to put more resources into employee volunteering. We know use of the abbreviation DEI has been through changes. The word &#8220;ESG&#8221; is also disappearing from report titles, down to 25% of S&amp;P 500 companies from 40% two years ago, but most executives say they aren&#8217;t changing what they actually do. &#8220;Greenhushing&#8221; is largely a messaging and visibility phenomenon, not an operational or strategic one. What else are companies reporting and what does it signal about the field?</p>
<p>Two topics are leaping off the page this season, and both sit squarely in Emblem&#8217;s work.</p>
<p>On harnessing the value of a diverse and inclusive workforce, the picture is genuinely mixed. A lot of companies have pulled back under a perception of legal and political pressure. But shareholders at Apple, Disney, and Costco rejected anti-DEI proposals this proxy season, and institutional investors haven&#8217;t abandoned the business case even when some executives have. I got a close look at this tension in 2022 while working on the BlackRock racial equity audit with colleagues at Working Ideal, and in 2021 while completing several years of work with a publicly traded bank on its diversity strategy. Financial institutions are getting pounded from multiple sides simultaneously, by institutional investors, state attorneys general, and civic action groups. Nobody knows where this lands. What everyone should factor in regardless of any other element: Latino and Black consumer power is already passing $6 trillion per year according to the National Urban League, and Harlem Capital reports that US investors of color are the fastest growing group in the stock market. The business case for smart engagement of diverse stakeholders is not going away.</p>
<p>Employee volunteering deserves particular attention right now. Benevity&#8217;s 2026 State of Corporate Volunteering report, released in March and tracking 2025 activity, logged 23.7 million approved volunteer hours last year, up 175% since 2019, with nearly 1.9 million unique employee volunteers. Companies aren&#8217;t doing this for external social impact alone. Employees who participate in purpose programs are 52% less likely to leave, and volunteering is the only workplace intervention among 90 studied that improved employee well-being across the board. Retention matters, replacement costs are high, and people want to work somewhere that partners with them to create meaning.</p>
<p>But the data has a sharp edge. Most companies are increasing volunteering budgets, yet only about 20% of nonprofit leaders surveyed say corporate volunteers are contributing meaningfully to long-term organizational capacity. Hours logged is not always impact delivered. Benevity&#8217;s own conclusion is that the entire system needs re-imagining, and they say so plainly. A growing gap has opened between what nonprofits actually need and what companies are currently set up to deliver.</p>
<p>That gap is the most important story in this report. The companies doing this well have figured out, usually the hard way, that citizenship has to be integrated into how you actually operate, not managed separately and communicated strategically. The upstream work determines the downstream value. Skills-based volunteering, longer immersive engagements, and deeper nonprofit partnerships are showing real promise because they treat nonprofits as partners with specific needs rather than recipients of goodwill. Think AI training, micro-sabbaticals, and shared planning cycles. The field spans a wide range of engagement models, and there is innovation to be done on narrow scope projects and deeper engagements alike. The data is pointing the way. There&#8217;s also a dimension the data hasn&#8217;t fully captured: service transforms the volunteer, not just the community. We are wired to feel good about giving, and to gain something from deep engagements outside our routines. When companies help employees have that experience at depth, they&#8217;re doing something that goes well beyond retention metrics. That&#8217;s worth measuring, and worth building toward.</p>
<p>Nonprofit leaders have their own reckoning here. Typical volunteer programs aren&#8217;t solving their biggest problems, and the data confirms what many of them have known for years. The question is what they&#8217;re willing to ask for, and what corporate partners are actually able to deliver. Perhaps as telling as anything else in the field: more than half of companies surveyed are now turning to external expertise to design and execute their strategy effectively.</p>
<p>The full picture is still coming together. But when an industry&#8217;s own leading research firm calls for re-imagining the entire model, that&#8217;s worth taking seriously. When I have been an employer taking teams on volunteer service days with non-profit partners like City Year and the Food Project I have seen the value we created on site and the value we got for our own organization. Both were very real. On the flipside, I experienced the complexity of handling the incoming generosity of corporate volunteers in nonprofits where I have been in a leadership role. Not simple. Requires real touch and judgment.</p>
<p>The value is real and the business case is intact. What the field needs now is for employers, nonprofits, and the organizations that broker and build these relationships to reimagine them together. That is work worth doing and will reveal the path forward for everyone involved. And underneath all of it, the organizations that get this right will have individuals at the helm who are willing to ask hard questions, follow the data, and lead with clarity. That has always been the variable that matters most.</p>`,
  }
];
