const EMBLEM_POSTS = [
  {
    slug: "corporate-citizenship-still-counts",
    title: "Corporate Citizenship Still Counts. New Data Says All Parties Working Together Can Increase Impact.",
    date: "2026-04-07",
    dateDisplay: "April 7, 2026",
    readTime: "4 min read",
    tags: ["Corporate Citizenship", "DEI", "Employee Volunteering", "Nonprofit"],
    excerpt: "The headlines say corporate America is retreating from its commitments. The picture emerging from this spring\u2019s corporate citizenship reporting season is much more complicated than that.",
    body: `<p>The headlines say corporate America is retreating from its commitments. The picture emerging from this spring&#8217;s corporate citizenship reporting season is much more complicated than that. The best place to start is new data.</p>
<p>The Conference Board surveyed corporate citizenship leaders in January, and a summary of its findings is available through the Harvard Law Corporate Governance Forum. Budgets are holding. More than half of respondents expect to put more resources into employee volunteering. We know use of the abbreviation DEI has been through changes. The word &#8220;ESG&#8221; is also disappearing from report titles, down to 25% of S&amp;P 500 companies from 40% two years ago, but most executives say they aren&#8217;t changing what they actually do. &#8220;Greenhushing&#8221; is largely a messaging and visibility phenomenon, not an operational or strategic one. What else are companies reporting and what does it signal about the field?</p>
<p>Two topics are leaping off the page this season, and both sit squarely in Emblem&#8217;s work.</p>
<p>On harnessing the value of a diverse and inclusive workforce, the picture is genuinely mixed. A lot of companies have pulled back under a perception of legal and political pressure. But shareholders at Apple, Disney, and Costco rejected anti-DEI proposals this proxy season, and institutional investors haven&#8217;t abandoned the business case even when some executives have. I got a close look at this tension in 2022 while working on the BlackRock racial equity audit with colleagues at Working Ideal, and in 2021 while completing several years of work with a publicly traded bank on its diversity strategy. Financial institutions are getting pounded from multiple sides simultaneously, by institutional investors, state attorneys general, and civic action groups. Nobody knows where this lands. What everyone should factor in regardless of any other element: Latino and Black consumer power is already passing $6 trillion per year according to the National Urban League, and Harlem Capital reports that US investors of color are the fastest growing group in the stock market. The business case for smart engagement of diverse stakeholders is not going away.</p>
<p>Employee volunteering deserves particular attention right now. Benevity&#8217;s 2026 State of Corporate Volunteering report, released in March and tracking 2025 activity, logged 23.7 million approved volunteer hours last year, up 175% since 2019, with nearly 1.9 million unique employee volunteers. Companies aren&#8217;t doing this for external social impact alone. Employees who participate in purpose programs are 52% less likely to leave, and volunteering is the only workplace intervention among 90 studied that improved employee well-being across the board. Retention matters, replacement costs are high, and people want to work somewhere that partners with them to create meaning.</p>
<p>But the data has a sharp edge. Most companies are increasing volunteering budgets, yet only about 20% of nonprofit leaders surveyed say corporate volunteers are contributing meaningfully to long-term organizational capacity. Hours logged is not always impact delivered. Benevity&#8217;s own conclusion is that the entire system needs re-imagining, and they say so plainly. A growing gap has opened between what nonprofits actually need and what companies are currently set up to deliver.</p>
<p>That gap is the most important story in this report. The companies doing this well have figured out, usually the hard way, that citizenship has to be integrated into how you actually operate, not managed separately and communicated strategically. The upstream work determines the downstream value. Skills-based volunteering, longer immersive engagements, and deeper nonprofit partnerships are showing real promise because they treat nonprofits as partners with specific needs rather than recipients of goodwill. Think AI training, micro-sabbaticals, and shared planning cycles. The field spans a wide range of engagement models, and there is innovation to be done on narrow scope projects and deeper engagements alike. The data is pointing the way. There&#8217;s also a dimension the data hasn&#8217;t fully captured: service transforms the volunteer, not just the community. We are wired to feel good about giving, and to gain something from deep engagements outside our routines. When companies help employees have that experience at depth, they&#8217;re doing something that goes well beyond retention metrics. That&#8217;s worth measuring, and worth building toward.</p>
<p>Nonprofit leaders have their own reckoning here. Typical volunteer programs aren&#8217;t solving their biggest problems, and the data confirms what many of them have known for years. The question is what they&#8217;re willing to ask for, and what corporate partners are actually able to deliver. Perhaps as telling as anything else in the field: more than half of companies surveyed are now turning to external expertise to design and execute their strategy effectively.</p>
<p>The full picture is still coming together. But when an industry&#8217;s own leading research firm calls for re-imagining the entire model, that&#8217;s worth taking seriously. When I have been an employer taking teams on volunteer service days with non-profit partners like City Year and the Food Project I have seen the value we created on site and the value we got for our own organization. Both were very real. On the flipside, I experienced the complexity of handling the incoming generosity of corporate volunteers in nonprofits where I have been in a leadership role. Not simple. Requires real touch and judgment.</p>
<p>The value is real and the business case is intact. What the field needs now is for employers, nonprofits, and the organizations that broker and build these relationships to reimagine them together. That is work worth doing and will reveal the path forward for everyone involved. And underneath all of it, the organizations that get this right will have individuals at the helm who are willing to ask hard questions, follow the data, and lead with clarity. That has always been the variable that matters most.</p>`,
    byline: "Andy Tarsy is Principal at Emblem Strategic and a trustee at Franklin Cummings Institute of Technology. He is co-founder and former President of the Alliance for Business Leadership."
  }
];